name: Docker Image CI

on:
  release:
    types: [created]
  workflow_dispatch:


jobs:

  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          push: true
          tags:  sigalen/sentry_tunnel:latest
