name: Docker Image CI

on:
  release:
    types: [created]
  workflow_dispatch:


jobs:

  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate tags
        id: docker_tags
        uses: dnaka91/action-docker-tags@v0.1

      - name: Build and push
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          push: true
          tags: ${{ steps.docker_tags.outputs.tags }}

